# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Epithet < Formula
  desc "SSH certificate authority that makes SSH certificates easy to use"
  homepage "https://github.com/epithet-ssh/epithet"
  version "0.2.8"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/epithet-ssh/epithet/releases/download/v0.2.8/epithet_0.2.8_darwin_amd64.tar.gz"
      sha256 "39885a48b49f9b1be0c769c6bb144dac25753ce05c7dce4f9e6d1e7650b90d41"

      def install
        bin.install "epithet"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/epithet-ssh/epithet/releases/download/v0.2.8/epithet_0.2.8_darwin_arm64.tar.gz"
      sha256 "e7a0002a0b1f718e7ff8784dccdac85e5cb8b6c256848e0ffa02e6377791dfc5"

      def install
        bin.install "epithet"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/epithet-ssh/epithet/releases/download/v0.2.8/epithet_0.2.8_linux_amd64.tar.gz"
      sha256 "229e2c26c2544ce94f3883fd730f02b610aafd56d578eeaaea1b4194fb96c41f"
      def install
        bin.install "epithet"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/epithet-ssh/epithet/releases/download/v0.2.8/epithet_0.2.8_linux_arm64.tar.gz"
      sha256 "5f23cbd3b8bc4e377eab87b4e0bf4666e61a16f6ae1b529fa0dbed150111ff77"
      def install
        bin.install "epithet"
      end
    end
  end
end
