# This file was generated by GoReleaser. DO NOT EDIT.
cask "epithet" do
  version "0.14.1"

  on_macos do
    on_intel do
      url "https://github.com/epithet-ssh/epithet/releases/download/v#{version}/epithet_#{version}_darwin_amd64.tar.gz"
      sha256 "5b5effa23f41a02c73b721953e8f755feb2a2df7fe6e7569d32d45b72389333d"
    end
    on_arm do
      url "https://github.com/epithet-ssh/epithet/releases/download/v#{version}/epithet_#{version}_darwin_arm64.tar.gz"
      sha256 "157146e399262b566131e5fb0410ccf447c74eb8f2a61b08d59260278a069721"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/epithet-ssh/epithet/releases/download/v#{version}/epithet_#{version}_linux_amd64.tar.gz"
      sha256 "4355237a7f859ab84d5055cafe9d70f0890def870da75fb7d23548d4db284231"
    end
    on_arm do
      url "https://github.com/epithet-ssh/epithet/releases/download/v#{version}/epithet_#{version}_linux_arm64.tar.gz"
      sha256 "8203f21a5cb56f8c4d7c27710277cc428120b3f1dd06847183f8fa17ce7734fe"
    end
  end

  name "epithet"
  desc "SSH certificate management"
  homepage "https://epithet.dev/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "epithet"

  # No zap stanza required

  caveats <<~EOS
    To start the agent:
      brew services start epithet
  EOS
end
