# Generated by epithet-packaging. Binary archives are hosted separately from this tap.
class Epithet < Formula
  desc "SSH certificate management"
  homepage 'https://epithet.dev'
  version '0.39.1'
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url 'https://pkg.epithet.dev/macos/releases/v0.39.1/epithet_0.39.1_darwin_arm64.tar.gz'
      sha256 '6032ce9f12d38c1ca65a7faee533ac6b40ca2af21311539735d1564f731f524b'
    else
      url 'https://pkg.epithet.dev/macos/releases/v0.39.1/epithet_0.39.1_darwin_amd64.tar.gz'
      sha256 '58fca49078efd5f460e4dcd69a3ea9ebd177509be36db10c087874a3d471d59b'
    end
  end

  depends_on :macos

  def install
    bin.install "epithet"
  end

  def caveats
    <<~EOS
      To start the agent:
        brew services start epithet
    EOS
  end

  service do
    run [opt_bin/"epithet", "--log-file=#{Dir.home}/Library/logs/dev.epithet/agent.log", "agent"]
    keep_alive true
    process_type :background
  end

  test do
    system bin/"epithet", "--version"
  end
end
