# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Epithet < Formula
  desc "SSH certificate management"
  homepage "https://epithet.dev/"
  version "0.23.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/epithet-ssh/epithet/releases/download/v0.23.0/epithet_0.23.0_darwin_amd64.tar.gz"
      sha256 "716d717fbe4862b6a6296e23dd41beca88ce57fe50a01613c7bd716f7e4bb2ec"

      define_method(:install) do
        bin.install "epithet"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/epithet-ssh/epithet/releases/download/v0.23.0/epithet_0.23.0_darwin_arm64.tar.gz"
      sha256 "15408507f06d9ebcb359b9a98275a1622615a7ec69bbcb540eb7b304652566d5"

      define_method(:install) do
        bin.install "epithet"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/epithet-ssh/epithet/releases/download/v0.23.0/epithet_0.23.0_linux_amd64.tar.gz"
      sha256 "3e0b94857153b933aaad40f8f6d66ebaf1e45bcbb035dd2bf885e40acfb098bc"
      define_method(:install) do
        bin.install "epithet"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/epithet-ssh/epithet/releases/download/v0.23.0/epithet_0.23.0_linux_arm64.tar.gz"
      sha256 "6e58412207c2ecfc238c0ce0ae3e12d86c95e555ae8d39ccadf0f71c08994196"
      define_method(:install) do
        bin.install "epithet"
      end
    end
  end

  def caveats
    <<~EOS
      To start the agent:
        brew services start epithet
    EOS
  end

  service do
    run [opt_bin/"epithet", "--log-file=#{Dir.home}/Library/logs/dev.epithet/agent.log", "agent"]
    keep_alive true
    process_type :background
  end

  test do
    system bin/"epithet", "--version"
  end
end
