# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Epithet < Formula
  desc "SSH certificate management"
  homepage "https://epithet.dev/"
  version "0.16.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/epithet-ssh/epithet/releases/download/v0.16.0/epithet_0.16.0_darwin_amd64.tar.gz"
      sha256 "a3c651f2f1c3b804a2f84ea99128d4fa3878828a62e11c0c7e6192e2e845d83f"

      define_method(:install) do
        bin.install "epithet"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/epithet-ssh/epithet/releases/download/v0.16.0/epithet_0.16.0_darwin_arm64.tar.gz"
      sha256 "083e935afac0972514ec841bc2be18f66952a6ffb038d7f7e1d80906ce86a584"

      define_method(:install) do
        bin.install "epithet"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/epithet-ssh/epithet/releases/download/v0.16.0/epithet_0.16.0_linux_amd64.tar.gz"
      sha256 "c1fa20889f0559b2a45a4c9406c1160ba5f0abc2c5f4bec49de76140c9240c66"
      define_method(:install) do
        bin.install "epithet"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/epithet-ssh/epithet/releases/download/v0.16.0/epithet_0.16.0_linux_arm64.tar.gz"
      sha256 "929b22d8725a0ed101086edfa1dfe60ac07058bdcc49cf451c62e407685e6b8c"
      define_method(:install) do
        bin.install "epithet"
      end
    end
  end

  def caveats
    <<~EOS
      To start the agent:
        brew services start epithet
    EOS
  end

  service do
    run [opt_bin/"epithet", "--log-file=#{Dir.home}/Library/logs/dev.epithet/agent.log", "agent"]
    keep_alive true
    process_type :background
  end

  test do
    system bin/"epithet", "--version"
  end
end
